//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CusID { get; set; }
        public string CusName { get; set; }
        public string CusType { get; set; }
        public int CusIDCard { get; set; }
        public string CusAddress { get; set; }
    }
}
