//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CatID { get; set; }
        public string CatName { get; set; }
        public string CatType { get; set; }
        public decimal Price { get; set; }
        public string Note { get; set; }
    }
}
